# Generated by Django 2.1.7 on 2019-02-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_pub',
            field=models.BooleanField(default=False),
        ),
    ]
